{
 "title": "HVAC",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "HVAC State Runtime vs Avg Outside Temperature",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"contrib/tomhollingworth/events\"\r\nimport \"math\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\nhvac_state_day_ends = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n  |> aggregateWindow(every: 24h, fn: last, createEmpty: false, column: \"_value\")\r\n\r\nhvac_states = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n\r\nhvac_states_daily = union(tables: [hvac_state_day_ends, hvac_states])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"])\r\n  |> events.duration(unit: 1s, columnName: \"elapsed\")\r\n  |> group(columns: [\"_value\"], mode:\"by\")\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: true, column: \"elapsed\")\r\n  |> fill(column: \"elapsed\", value: 0)\r\n  |> map(fn: (r) => ({r with elapsed_pct: math.round(x: (float(v: r.elapsed) / 86400.0) * 100.0) }))\r\n  |> filter(fn: (r) => r[\"_value\"] != \"idle\")\r\n  |> filter(fn: (r) => r[\"elapsed_pct\"] != 0)\r\n  |> rename(columns: {_value: \"state\"})\r\n  |> keep(columns: [\"_time\", \"elapsed_pct\", \"state\"])\r\n\r\n//yield(tables: hvac_states_daily, name: \"hvac_states_daily\")\r\n\r\noutside_temps = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Outside Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"friendly_name\"])\r\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"friendly_name\"], valueColumn: \"_value\")\r\n\r\njoin(tables: {hvac_states_daily, outside_temps}, on: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Avg HVAC Runtime Per Avg Outside Temperature",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"contrib/tomhollingworth/events\"\r\nimport \"math\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\nhvac_state_day_ends = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n  |> aggregateWindow(every: 24h, fn: last, createEmpty: false, column: \"_value\")\r\n\r\nhvac_states = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n\r\nhvac_states_daily = union(tables: [hvac_state_day_ends, hvac_states])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"])\r\n  |> events.duration(unit: 1s, columnName: \"elapsed\")\r\n  |> group(columns: [\"_value\"], mode:\"by\")\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: true, column: \"elapsed\")\r\n  |> fill(column: \"elapsed\", value: 0)\r\n  |> map(fn: (r) => ({r with elapsed_pct: math.round(x: (float(v: r.elapsed) / 86400.0) * 100.0) }))\r\n  |> filter(fn: (r) => r[\"_value\"] != \"idle\")\r\n  |> rename(columns: {_value: \"state\"})\r\n  |> keep(columns: [\"_time\", \"elapsed_pct\", \"state\"])\r\n\r\noutside_temps = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Outside Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"friendly_name\"])\r\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: math.round(x: r._value)}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"friendly_name\"], valueColumn: \"_value\")\r\n\r\n//yield(tables: outside_temps, name: \"outside_temps\")\r\n\r\njoin(tables: {hvac_states_daily, outside_temps}, on: [\"_time\"])\r\n  |> drop(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Percent HVAC State Per Day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"contrib/tomhollingworth/events\"\r\nimport \"math\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\nhvac_state_day_ends = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n  |> aggregateWindow(every: 24h, fn: last, createEmpty: false, column: \"_value\")\r\n\r\nhvac_states = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n\r\nunion(tables: [hvac_state_day_ends, hvac_states])\r\n  |> group()\r\n  |> sort(columns: [\"_time\"])\r\n  |> events.duration(unit: 1s, columnName: \"elapsed\")\r\n  |> group(columns: [\"_value\"], mode:\"by\")\r\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: true, column: \"elapsed\")\r\n  |> fill(column: \"elapsed\", value: 0)\r\n  |> map(fn: (r) => ({r with elapsed_pct: math.round(x: (float(v: r.elapsed) / 86400.0) * 100.0) }))\r\n  |> filter(fn: (r) => r[\"_value\"] != \"idle\")\r\n  |> drop(columns: [\"elapsed\"])\r\n"
    }
   ]
  },
  {
   "title": "Daily Outside Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\ntemps = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Outside Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> keep(columns: [\"_time\", \"friendly_name\", \"_value\"])\r\n\r\nmax_temp = temps\r\n  |> aggregateWindow(every: 24h, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with friendly_name: \"max\" }))\r\n  |> yield(name: \"max\")\r\n\r\navg_temp = temps\r\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with friendly_name: \"avg\" }))\r\n  |> yield(name: \"avg\")\r\n\r\nmin_temp = temps\r\n  |> aggregateWindow(every: 24h, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with friendly_name: \"min\" }))\r\n  |> yield(name: \"min\")"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"interpolate\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\nfrom(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Attic Temperature\" or r[\"friendly_name\"] == \"Basement Temperature\" or r[\"friendly_name\"] == \"Bedroom Temperature\" or r[\"friendly_name\"] == \"Kitchen Temperature\" or r[\"friendly_name\"] == \"Outside Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> interpolate.linear(every: 1h)\r\n  |> keep(columns: [\"_time\", \"friendly_name\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)"
    }
   ]
  },
  {
   "title": "HVAC State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"HVAC State\")\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Temperature Difference Between Floors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/New_York\")\r\n\r\nbedroom_temp = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Bedroom Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> filter(fn: (r) => exists r._value)\r\n\r\nkitchen_temp = from(bucket: \"home-assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"friendly_name\"] == \"Kitchen Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n  |> filter(fn: (r) => exists r._value)\r\n\r\njoin(tables: {bedroom_temp, kitchen_temp}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({r with diff: float(v: r._value_bedroom_temp - r._value_kitchen_temp)}))\r\n  |> keep(columns: [\"_time\", \"diff\"])"
    }
   ]
  }
 ]
}